# Generated by Django 4.1.2 on 2022-11-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart_data',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False)),
                ('books_and_quanty', models.TextField(max_length=10000)),
                ('user_id', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
