# Generated by Django 4.1.2 on 2022-11-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False)),
                ('books_and_quanty', models.TextField(max_length=10000)),
                ('user_id', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='cart_data',
        ),
    ]
