# Generated by Django 4.1.2 on 2022-11-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('book_rating', models.IntegerField()),
                ('review_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
