# Generated by Django 4.1.2 on 2022-10-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='person',
        ),
    ]
