# Generated by Django 4.1.2 on 2022-11-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0008_remove_book_seller_rating'),
        ('user_detail', '0004_person_seller_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_detail.person')),
            ],
        ),
    ]
