# Generated by Django 4.1.2 on 2022-11-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_data_user_id_alter_cart_data_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_data',
            name='user_id',
            field=models.IntegerField(default=-2),
            preserve_default=False,
        ),
    ]
