# Generated by Django 4.1.2 on 2022-11-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_data_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_data',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
