# Generated by Django 4.1.2 on 2022-11-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cart_data_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart_data", name="quantity", field=models.IntegerField(),
        ),
    ]
