# Generated by Django 4.1.2 on 2022-10-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0003_remove_person_id_person_user_id'),
        ('book', '0002_remove_book_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='user_detail.person'),
            preserve_default=False,
        ),
    ]
