# Generated by Django 4.1.2 on 2022-11-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_book_img_book_seller_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='seller_rating',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
