# Generated by Django 4.1.2 on 2022-11-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_book_rating_book_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='seller_rating',
        ),
    ]
