# Generated by Django 4.1.2 on 2022-11-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_remove_book_seller_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="user_id", field=models.IntegerField(),
        ),
    ]
